version: 2.1
jobs:
  compile:
   docker:
      - image: leon4rd/aosp:kernel
   resource_class: large
   steps:
      - run:
          no_output_timeout: 50m
          command: |
           git clone --depth 1 https://github.com/Risti699/Karamel.git -b JFla-Karamel kernel
           cd kernel
           curl https://raw.githubusercontent.com/leon4rd/myscripts/circleci-project-setup/build.sh | bash
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
